### ISSUE TITLE
Env with DCsync got MessagesTypesAndExceptions Caused by EntityStreamException

### ISSUE THREAD

**Issue by GuyGuterman** [thomsonreuters/CM-Well#497] opened 2018-02-08 13:42 UTC
In an environment with DCsync received over less than 24h (~15h) 370 times.
Retrieve TSVs failed due to HAProxy Shouts at the error that there is no body (unnecessarily) in the header.
That causes the BulkConsume/Consume to be restarted.

The env/system working in normal mode with no load or problems. (by dashboard)

Expected result: The number of times is high.
Actual result: The number of times will strive to be low to zero.

**Comment by e-orz** [comment] 2018-03-14 09:18
EntityStreamException is related to streams errors.
duplicate of #436

**Closed by e-orz** 2018-03-14 09:18 UTC
Labels: bug

**Comment by GuyGuterman** [comment] 2018-03-18 08:57
The problem is not DCsync but due to the communication is stuck/cut.
Streaming infotons fail [#436](https://github.com/thomsonreuters/CM-Well/issues/436)
Moving to Done.
