### ISSUE TITLE
Q version on update env found ambiguity ID with two "current":true and different datacenter ns-monitor

### ISSUE THREAD

**Issue by GuyGuterman** [thomsonreuters/CM-Well#501] opened 2018-02-13 13:15 UTC
New option of finding Ambiguity/duplicates helped to find duplicate ID: ACA.

1.  ?op=x-info showing two existing "current":true (at es)
2.  two different dataCenter with bit-exact fields.

> **Steps to restore:**

1. use ns-monitor for find Ambiguity
2. search by ?op to find how many infotons will be founded at result
3. search by ?op=x-info duplicate ID
4. each result find uuid and open in (ex ?format<type>)

> **expected result**

⚠️ No Ambiguity/duplicates
⚠️ Infoton must have JUST one "current": true

**Comment by hochgi** [comment] 2018-02-21 04:11
duplicate of #465

**Closed by hochgi** 2018-02-21 04:11 UTC
Labels: archive, bug, duplicate
