### ISSUE TITLE
STP - Agent restarted after failure of reading the config infotons

### ISSUE THREAD

**Issue by yanpom** [thomsonreuters/CM-Well#516] opened 2018-02-19 12:33 UTC
Run dealsjvscore agent
After few minutes of normal work, there was exception in agent.log:
 WARN  c.t.d.sparql.SparqlProcessorManager  - The manager failed to parse the json of the config infotons failed with exception! The json was: {
  "success" : false,
  "error" : "Failed to execute phase [fetch], [reduce] "
}
After several minutes, agent stopped and started again
After the restart, agent continue working smoothly

**Comment by nicklester** [comment] 2018-02-19 14:08
Is this a duplicate of #404 ?

**Comment by e-orz** [comment] 2018-02-19 14:44
The error itself is a duplicate. But the fact that there was a restart isn't. According to Yan only one sensor/yaml stopped and all the other continued, which is strange.

**Comment by nicklester** [comment] 2018-02-19 14:56
@e-orz yeah I was speaking to @yanpom about the same. I am going to look into the logs shortly

**Comment by nicklester** [comment] 2018-06-18 20:11
Will retry config read upon failure..

**Comment by YoniMataraso** [comment] 2018-06-25 15:14
Let's add retry logic into the configuration load process

**Comment by nicklester** [comment] 2018-07-10 09:00
The SparqlProcessorManager will try again in 30 seconds regardless so I think we can close the ticket. Tested and demonstrated this is the case. Now that agents persist stats and token position the agent starting again does not cause us any problemz

**Comment by nicklester** [comment] 2018-07-10 09:01
Additionally, not observed this problem in recent logs

**Closed by nicklester** 2018-07-10 09:00 UTC
Labels: STP, bug
